name: organiza_ae
description: "A flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0' # Atualizei para uma faixa mais comum e compatível

dependencies:
  flutter:
    sdk: flutter

  # Pacotes para o banco de dados local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1 # Ajuda o Hive a encontrar onde salvar os dados

  # Gerenciamento de Estado
  flutter_riverpod: ^3.0.0

  # Utilitário para gerar IDs únicos para produtos e categorias
  uuid: ^4.3.3

  share_plus: ^7.2.2

  intl: ^0.19.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Pacotes que geram código automaticamente para o Hive
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true